### ISSUE TITLE
Hide square at beginning

### ISSUE THREAD

**Issue by Myzel394** [fabridamicelli/cronex.nvim#1]
Is there some way to hide the square at the beginning? I'd rather instead wanna show this clock:

![image](https://github.com/fabridamicelli/cronex.nvim/assets/50424412/85fefaff-5342-4870-b19f-3489d76d6bf7)

**Comment by fabridamicelli** [comment]
I like that idea. I should make that configuration more accessible. But for now you can go with this (which is a bit of a hack but should work fine):

```lua
return {
    "fabridamicelli/cronex.nvim",
    config = function()
        -- Initialize module (important to create namespace)
        require("cronex").setup({})
        -- Grab the namespace that Cronex uses for the explanations
        local ns = vim.api.nvim_get_namespaces()["cronex"]
        -- Override the config only for that namespace
        vim.diagnostic.config({
        virtual_text = {
            prefix = "󰥔"
        }
      }, ns
    )
    end
}
```

It looks like this:

![use-clock](https://github.com/fabridamicelli/cronex.nvim/assets/40115969/1dfb6c49-091d-4e55-a3b7-e14ca32b80d7)
